Feature/l3 100
digicatapult/dscp-matchmaker-api pull request #142
Opened 2023-09-01 15:56 UTC by Ellenn-A

Hi Guys, 

Could you pls have a look on the changes I have made? 
I have separated the seed data into separate files that tests use. 

Also sth odd is going on with the linting on the files I have added pls let me know how to fix that. 

For chain.test.ts there was the seed file being run before the test, but I have removed it as we don't need any seed data for that test. I replaced it with cleanup() but I'm not sure if we need that either. 

I have left the index file (original seed file) in, but it's not used anywhere anymore. Would you want me to remove it?

2023-09-01 16:22 UTC, dblane-digicatapult requested changes
Looks good.  Try running the linter with the fix argument to fix the linting.
Delete the old seed index file.

2023-09-01 16:22 UTC, dblane-digicatapult commented on docker-compose-3-persona.yml
> +      --ws-max-connections 512
The additional `ws-max-connections` argument is not needed in `docker-compose-3-persona.yml` as we do not run automated tests against this file.

2023-09-01 16:22 UTC, dblane-digicatapult commented on test/seeds/index.ts
> +// }
Delete file.

2023-09-04 09:54 UTC, mattdean-digicatapult reviewed
looks like a big improvement to me. Happy once @dblane-digicatapult is happy

2023-09-04 10:34 UTC, dblane-digicatapult approved these changes

2023-09-04 10:39 UTC, merged